-- Inserir parâmetros sistema
insert into parametros (id, exibir_remetente, exibir_carimbo_impresso, exibir_carimbo_mala_direta) values (1, false, false, false);

-- Inserir estados
insert into estados (descricao, uf) values ('Acre', 'AC');
insert into estados (descricao, uf) values ('Alagoas', 'AL');
insert into estados (descricao, uf) values ('Amapá', 'AP');
insert into estados (descricao, uf) values ('Amazonas', 'AM');
insert into estados (descricao, uf) values ('Bahia', 'BA');
insert into estados (descricao, uf) values ('Ceará', 'CE');
insert into estados (descricao, uf) values ('Distrito Federal', 'DF');
insert into estados (descricao, uf) values ('Espírito Santo', 'ES');		 
insert into estados (descricao, uf) values ('Goiás', 'GO');
insert into estados (descricao, uf) values ('Maranhão', 'MA');		 
insert into estados (descricao, uf) values ('Mato Grosso', 'MT');
insert into estados (descricao, uf) values ('Mato Grosso do Sul', 'MS');		 
insert into estados (descricao, uf) values ('Minas Gerais', 'MG');
insert into estados (descricao, uf) values ('Pará', 'PA');		 
insert into estados (descricao, uf) values ('Paraíba', 'PB');
insert into estados (descricao, uf) values ('Paraná', 'PR');		 
insert into estados (descricao, uf) values ('Pernambuco', 'PE');
insert into estados (descricao, uf) values ('Piauí', 'PI');		 
insert into estados (descricao, uf) values ('Rio de Janeiro', 'RJ');
insert into estados (descricao, uf) values ('Rio Grande do Norte', 'RN');		 
insert into estados (descricao, uf) values ('Rio Grande do Sul', 'RS');
insert into estados (descricao, uf) values ('Rondônia', 'RO');		 
insert into estados (descricao, uf) values ('Roraima', 'RR');
insert into estados (descricao, uf) values ('Santa Catarina', 'SC');		 
insert into estados (descricao, uf) values ('São Paulo', 'SP');
insert into estados (descricao, uf) values ('Sergipe', 'SE');		 
insert into estados (descricao, uf) values ('Tocantins', 'TO');

-- Inserir materiais do estudo
insert into materiais_estudo (nome, numero_ordem, ativo, corrigible, tipo_envelope) values ('INTRODUTÓRIA', 1, true, true, 1);
insert into materiais_estudo (nome, numero_ordem, ativo, corrigible, tipo_envelope) values ('DEUS TEM FALADO', 2, true, true, 2);
insert into materiais_estudo (nome, numero_ordem, ativo, corrigible, tipo_envelope) values ('CONHECENDO JESUS', 3, true, true, 2);
insert into materiais_estudo (nome, numero_ordem, ativo, corrigible, tipo_envelope) values ('ESTAS SÃO AS BOAS NOVAS', 4, true, true, 2);
insert into materiais_estudo (nome, numero_ordem, ativo, corrigible, tipo_envelope) values ('NASCIDOS DA ÁGUA E DO ESPÍRITO', 5, true, true, 2);
insert into materiais_estudo (nome, numero_ordem, ativo, corrigible, tipo_envelope) values ('O QUE A BÍBLIA DIZ 1', 6, true, true, 2);
insert into materiais_estudo (nome, numero_ordem, ativo, corrigible, tipo_envelope) values ('O QUE A BÍBLIA DIZ 2', 7, true, true, 2);
insert into materiais_estudo (nome, numero_ordem, ativo, corrigible, tipo_envelope) values ('O QUE A BÍBLIA DIZ 3', 8, true, true, 2);
insert into materiais_estudo (nome, numero_ordem, ativo, corrigible, tipo_envelope) values ('O QUE A BÍBLIA DIZ 4', 9, true, true, 2);
insert into materiais_estudo (nome, numero_ordem, ativo, corrigible, tipo_envelope) values ('O QUE A BÍBLIA DIZ 5', 10, true, true, 2);
insert into materiais_estudo (nome, numero_ordem, ativo, corrigible, tipo_envelope) values ('O QUE A BÍBLIA DIZ 6', 11, true, true, 2);
insert into materiais_estudo (nome, numero_ordem, ativo, corrigible, tipo_envelope) values ('O QUE A BÍBLIA DIZ 7', 12, true, true, 2);
insert into materiais_estudo (nome, numero_ordem, ativo, corrigible, tipo_envelope) values ('O QUE A BÍBLIA DIZ 8', 13, true, true, 2);
insert into materiais_estudo (nome, numero_ordem, ativo, corrigible, tipo_envelope) values ('O QUE A BÍBLIA DIZ 9', 14, true, true, 2);
insert into materiais_estudo (nome, numero_ordem, ativo, corrigible, tipo_envelope) values ('O QUE A BÍBLIA DIZ 10', 15, true, true, 2);
insert into materiais_estudo (nome, numero_ordem, ativo, corrigible, tipo_envelope) values ('O QUE A BÍBLIA DIZ 11', 16, true, true, 2);
insert into materiais_estudo (nome, numero_ordem, ativo, corrigible, tipo_envelope) values ('A IGREJA BÍBLICA 1', 17, true, true, 3);
insert into materiais_estudo (nome, numero_ordem, ativo, corrigible, tipo_envelope) values ('A IGREJA BÍBLICA 2', 18, true, true, 3);
insert into materiais_estudo (nome, numero_ordem, ativo, corrigible, tipo_envelope) values ('A IGREJA BÍBLICA 3', 19, true, true, 3);
insert into materiais_estudo (nome, numero_ordem, ativo, corrigible, tipo_envelope) values ('A IGREJA BÍBLICA 4', 20, true, true, 3);
insert into materiais_estudo (nome, numero_ordem, ativo, corrigible, tipo_envelope) values ('A IGREJA BÍBLICA 5', 21, true, true, 3);
insert into materiais_estudo (nome, numero_ordem, ativo, corrigible, tipo_envelope) values ('A IGREJA BÍBLICA 6', 22, true, true, 3);
insert into materiais_estudo (nome, numero_ordem, ativo, corrigible, tipo_envelope) values ('A IGREJA BÍBLICA 7', 23, true, true, 3);
insert into materiais_estudo (nome, numero_ordem, ativo, corrigible, tipo_envelope) values ('A IGREJA BÍBLICA 8', 24, true, true, 3);
insert into materiais_estudo (nome, numero_ordem, ativo, corrigible, tipo_envelope) values ('A IGREJA BÍBLICA 9', 25, true, true, 3);
insert into materiais_estudo (nome, numero_ordem, ativo, corrigible, tipo_envelope) values ('A IGREJA BÍBLICA 10', 26, true, true, 3);
insert into materiais_estudo (nome, numero_ordem, ativo, corrigible, tipo_envelope) values ('A IGREJA BÍBLICA 11', 27, true, true, 3);
insert into materiais_estudo (nome, numero_ordem, ativo, corrigible, tipo_envelope) values ('A IGREJA BÍBLICA 12', 28, true, true, 3);
insert into materiais_estudo (nome, numero_ordem, ativo, corrigible, tipo_envelope) values ('A IGREJA BÍBLICA 13', 29, true, true, 3);
insert into materiais_estudo(nome, numero_ordem, ativo, corrigible, tipo_envelope) values ('CRISTÃO FIEL 1', 30, true, true, 3);
insert into materiais_estudo(nome, numero_ordem, ativo, corrigible, tipo_envelope) values ('CRISTÃO FIEL 2', 31, true, true, 3);
insert into materiais_estudo(nome, numero_ordem, ativo, corrigible, tipo_envelope) values ('CRISTÃO FIEL 3', 32, true, true, 3);
insert into materiais_estudo(nome, numero_ordem, ativo, corrigible, tipo_envelope) values ('CRISTÃO FIEL 4', 33, true, true, 3);
insert into materiais_estudo(nome, numero_ordem, ativo, corrigible, tipo_envelope) values ('CRISTÃO FIEL 5', 34, true, true, 3);
insert into materiais_estudo(nome, numero_ordem, ativo, corrigible, tipo_envelope) values ('CRISTÃO FIEL 6', 35, true, true, 3);
insert into materiais_estudo(nome, numero_ordem, ativo, corrigible, tipo_envelope) values ('CRISTÃO FIEL 7', 36, true, true, 3);
insert into materiais_estudo(nome, numero_ordem, ativo, corrigible, tipo_envelope) values ('CRISTÃO FIEL 8', 37, true, true, 3);
insert into materiais_estudo(nome, numero_ordem, ativo, corrigible, tipo_envelope) values ('CRISTÃO FIEL 9', 38, true, true, 3);
insert into materiais_estudo(nome, numero_ordem, ativo, corrigible, tipo_envelope) values ('CRISTÃO FIEL 10', 39, true, true, 3);
insert into materiais_estudo(nome, numero_ordem, ativo, corrigible, tipo_envelope) values ('CRISTÃO FIEL 11', 40, true, true, 3);
insert into materiais_estudo(nome, numero_ordem, ativo, corrigible, tipo_envelope) values ('CRISTÃO FIEL 12', 41, true, true, 3);
insert into materiais_estudo(nome, numero_ordem, ativo, corrigible, tipo_envelope) values ('CRISTÃO FIEL 13', 42, true, true, 3);
insert into materiais_estudo(nome, numero_ordem, ativo, corrigible, tipo_envelope) values ('CRISTÃO FIEL 14', 43, true, true, 3);
insert into materiais_estudo(nome, numero_ordem, ativo, corrigible, tipo_envelope) values ('CRISTÃO FIEL 15', 44, true, true, 3);
insert into materiais_estudo(nome, numero_ordem, ativo, corrigible, tipo_envelope) values ('CRISTÃO FIEL 16', 45, true, true, 3);
insert into materiais_estudo(nome, numero_ordem, ativo, corrigible, tipo_envelope) values ('CRISTÃO FIEL 17', 46, true, true, 3);
insert into materiais_estudo(nome, numero_ordem, ativo, corrigible, tipo_envelope) values ('CRISTÃO FIEL 18', 47, true, true, 3);
insert into materiais_estudo(nome, numero_ordem, ativo, corrigible, tipo_envelope) values ('CRISTÃO FIEL 19', 48, true, true, 3);
insert into materiais_estudo(nome, numero_ordem, ativo, corrigible, tipo_envelope) values ('CRISTÃO FIEL 20', 49, true, true, 3);
insert into materiais_estudo (nome, numero_ordem, ativo, corrigible, tipo_envelope) values ('CRISTIANISMO EM AÇÃO 1', 50, true, true, 3);
insert into materiais_estudo (nome, numero_ordem, ativo, corrigible, tipo_envelope) values ('CRISTIANISMO EM AÇÃO 2', 51, true, true, 3);
insert into materiais_estudo (nome, numero_ordem, ativo, corrigible, tipo_envelope) values ('CRISTIANISMO EM AÇÃO 3', 52, true, true, 3);
insert into materiais_estudo (nome, numero_ordem, ativo, corrigible, tipo_envelope) values ('CRISTIANISMO EM AÇÃO 4', 53, true, true, 3);
insert into materiais_estudo (nome, numero_ordem, ativo, corrigible, tipo_envelope) values ('CRISTIANISMO EM AÇÃO 5', 54, true, true, 3);
insert into materiais_estudo (nome, numero_ordem, ativo, corrigible, tipo_envelope) values ('CRISTIANISMO EM AÇÃO 6', 55, true, true, 3);
insert into materiais_estudo (nome, numero_ordem, ativo, corrigible, tipo_envelope) values ('CRISTIANISMO EM AÇÃO 7', 56, true, true, 3);
insert into materiais_estudo (nome, numero_ordem, ativo, corrigible, tipo_envelope) values ('CRISTIANISMO EM AÇÃO 8', 57, true, true, 3);
insert into materiais_estudo (nome, numero_ordem, ativo, corrigible, tipo_envelope) values ('CRISTIANISMO EM AÇÃO 9', 58, true, true, 3);
insert into materiais_estudo (nome, numero_ordem, ativo, corrigible, tipo_envelope) values ('CRISTIANISMO EM AÇÃO 10', 59, true, true, 3);
insert into materiais_estudo (nome, numero_ordem, ativo, corrigible, tipo_envelope) values ('CRISTIANISMO EM AÇÃO 11', 60, true, true, 3);
insert into materiais_estudo (nome, numero_ordem, ativo, corrigible, tipo_envelope) values ('CRISTIANISMO EM AÇÃO 12', 61, true, true, 3);
insert into materiais_estudo (nome, numero_ordem, ativo, corrigible, tipo_envelope) values ('CRISTIANISMO EM AÇÃO 13', 62, true, true, 3);
