-- Inserir parâmetros sistema
insert into parametros (id, exibir_remetente, exibir_carimbo_impresso, exibir_carimbo_mala_direta) values (1, false, false, false);

-- Inserir estados
insert into estados (descricao, uf) values ('Acre', 'AC');
insert into estados (descricao, uf) values ('Alagoas', 'AL');
insert into estados (descricao, uf) values ('Amapá', 'AP');
insert into estados (descricao, uf) values ('Amazonas', 'AM');
insert into estados (descricao, uf) values ('Bahia', 'BA');
insert into estados (descricao, uf) values ('Ceará', 'CE');
insert into estados (descricao, uf) values ('Distrito Federal', 'DF');
insert into estados (descricao, uf) values ('Espírito Santo', 'ES');		 
insert into estados (descricao, uf) values ('Goiás', 'GO');
insert into estados (descricao, uf) values ('Maranhão', 'MA');		 
insert into estados (descricao, uf) values ('Mato Grosso', 'MT');
insert into estados (descricao, uf) values ('Mato Grosso do Sul', 'MS');		 
insert into estados (descricao, uf) values ('Minas Gerais', 'MG');
insert into estados (descricao, uf) values ('Pará', 'PA');		 
insert into estados (descricao, uf) values ('Paraíba', 'PB');
insert into estados (descricao, uf) values ('Paraná', 'PR');		 
insert into estados (descricao, uf) values ('Pernambuco', 'PE');
insert into estados (descricao, uf) values ('Piauí', 'PI');		 
insert into estados (descricao, uf) values ('Rio de Janeiro', 'RJ');
insert into estados (descricao, uf) values ('Rio Grande do Norte', 'RN');		 
insert into estados (descricao, uf) values ('Rio Grande do Sul', 'RS');
insert into estados (descricao, uf) values ('Rondônia', 'RO');		 
insert into estados (descricao, uf) values ('Roraima', 'RR');
insert into estados (descricao, uf) values ('Santa Catarina', 'SC');		 
insert into estados (descricao, uf) values ('São Paulo', 'SP');
insert into estados (descricao, uf) values ('Sergipe', 'SE');		 
insert into estados (descricao, uf) values ('Tocantins', 'TO');

-- Inserir materiais do estudo
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('INTRODUTÓRIA', 1, 1);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('DEUS TEM FALADO', 2, 2);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('CONHECENDO JESUS', 3, 2);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('ESTAS SÃO AS BOAS NOVAS', 4, 2);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('NASCIDOS DA ÁGUA E DO ESPÍRITO', 5, 2);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('O QUE A BÍBLIA DIZ 1', 6, 2);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('O QUE A BÍBLIA DIZ 2', 7, 2);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('O QUE A BÍBLIA DIZ 3', 8, 2);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('O QUE A BÍBLIA DIZ 4', 9, 2);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('O QUE A BÍBLIA DIZ 5', 10, 2);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('O QUE A BÍBLIA DIZ 6', 11, 2);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('O QUE A BÍBLIA DIZ 7', 12, 2);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('O QUE A BÍBLIA DIZ 8', 13, 2);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('O QUE A BÍBLIA DIZ 9', 14, 2);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('O QUE A BÍBLIA DIZ 10', 15, 2);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('O QUE A BÍBLIA DIZ 11', 16, 2);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('A IGREJA BÍBLICA 1', 17, 3);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('A IGREJA BÍBLICA 2', 18, 3);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('A IGREJA BÍBLICA 3', 19, 3);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('A IGREJA BÍBLICA 4', 20, 3);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('A IGREJA BÍBLICA 5', 21, 3);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('A IGREJA BÍBLICA 6', 22, 3);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('A IGREJA BÍBLICA 7', 23, 3);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('A IGREJA BÍBLICA 8', 24, 3);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('A IGREJA BÍBLICA 9', 25, 3);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('A IGREJA BÍBLICA 10', 26, 3);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('A IGREJA BÍBLICA 11', 27, 3);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('A IGREJA BÍBLICA 12', 28, 3);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('A IGREJA BÍBLICA 13', 29, 3);
insert into materiais_estudo(nome, numero_ordem, tipo_envelope) values ('CRISTÃO FIEL 1', 30, 3);
insert into materiais_estudo(nome, numero_ordem, tipo_envelope) values ('CRISTÃO FIEL 2', 31, 3);
insert into materiais_estudo(nome, numero_ordem, tipo_envelope) values ('CRISTÃO FIEL 3', 32, 3);
insert into materiais_estudo(nome, numero_ordem, tipo_envelope) values ('CRISTÃO FIEL 4', 33, 3);
insert into materiais_estudo(nome, numero_ordem, tipo_envelope) values ('CRISTÃO FIEL 5', 34, 3);
insert into materiais_estudo(nome, numero_ordem, tipo_envelope) values ('CRISTÃO FIEL 6', 35, 3);
insert into materiais_estudo(nome, numero_ordem, tipo_envelope) values ('CRISTÃO FIEL 7', 36, 3);
insert into materiais_estudo(nome, numero_ordem, tipo_envelope) values ('CRISTÃO FIEL 8', 37, 3);
insert into materiais_estudo(nome, numero_ordem, tipo_envelope) values ('CRISTÃO FIEL 9', 38, 3);
insert into materiais_estudo(nome, numero_ordem, tipo_envelope) values ('CRISTÃO FIEL 10', 39, 3);
insert into materiais_estudo(nome, numero_ordem, tipo_envelope) values ('CRISTÃO FIEL 11', 40, 3);
insert into materiais_estudo(nome, numero_ordem, tipo_envelope) values ('CRISTÃO FIEL 12', 41, 3);
insert into materiais_estudo(nome, numero_ordem, tipo_envelope) values ('CRISTÃO FIEL 13', 42, 3);
insert into materiais_estudo(nome, numero_ordem, tipo_envelope) values ('CRISTÃO FIEL 14', 43, 3);
insert into materiais_estudo(nome, numero_ordem, tipo_envelope) values ('CRISTÃO FIEL 15', 44, 3);
insert into materiais_estudo(nome, numero_ordem, tipo_envelope) values ('CRISTÃO FIEL 16', 45, 3);
insert into materiais_estudo(nome, numero_ordem, tipo_envelope) values ('CRISTÃO FIEL 17', 46, 3);
insert into materiais_estudo(nome, numero_ordem, tipo_envelope) values ('CRISTÃO FIEL 18', 47, 3);
insert into materiais_estudo(nome, numero_ordem, tipo_envelope) values ('CRISTÃO FIEL 19', 48, 3);
insert into materiais_estudo(nome, numero_ordem, tipo_envelope) values ('CRISTÃO FIEL 20', 49, 3);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('CRISTIANISMO EM AÇÃO 1', 50, 3);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('CRISTIANISMO EM AÇÃO 2', 51, 3);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('CRISTIANISMO EM AÇÃO 3', 52, 3);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('CRISTIANISMO EM AÇÃO 4', 53, 3);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('CRISTIANISMO EM AÇÃO 5', 54, 3);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('CRISTIANISMO EM AÇÃO 6', 55, 3);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('CRISTIANISMO EM AÇÃO 7', 56, 3);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('CRISTIANISMO EM AÇÃO 8', 57, 3);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('CRISTIANISMO EM AÇÃO 9', 58, 3);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('CRISTIANISMO EM AÇÃO 10', 59, 3);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('CRISTIANISMO EM AÇÃO 11', 60, 3);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('CRISTIANISMO EM AÇÃO 12', 61, 3);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('CRISTIANISMO EM AÇÃO 13', 62, 3);
