alter table alunos drop constraint endereco_fk
alter table atividades_estudo drop constraint aluno_fk
alter table atividades_estudo drop constraint material_fk
alter table atividades_estudo drop constraint postagem_fk
alter table caracterizacoes drop constraint aluno_fk
alter table enderecos drop constraint estado_fk
alter table presidiarios drop constraint presidio_fk
alter table presidiarios drop constraint caracterizacao_fk
alter table presidios drop constraint endereco_fk
drop table if exists alunos cascade
drop table if exists atividades_estudo cascade
drop table if exists caracterizacoes cascade
drop table if exists enderecos cascade
drop table if exists estados cascade
drop table if exists materiais_estudo cascade
drop table if exists postagens cascade
drop table if exists presidiarios cascade
drop table if exists presidios cascade
