-- Inserir estados
insert into estados (descricao, uf) values ('Acre', 'AC');
insert into estados (descricao, uf) values ('Alagoas', 'AL');
insert into estados (descricao, uf) values ('Amapá', 'AP');
insert into estados (descricao, uf) values ('Amazonas', 'AM');
insert into estados (descricao, uf) values ('Bahia', 'BA');
insert into estados (descricao, uf) values ('Ceará', 'CE');
insert into estados (descricao, uf) values ('Distrito Federal', 'DF');
insert into estados (descricao, uf) values ('Espírito Santo', 'ES');		 
insert into estados (descricao, uf) values ('Goiás', 'GO');
insert into estados (descricao, uf) values ('Maranhão', 'MA');		 
insert into estados (descricao, uf) values ('Mato Grosso', 'MT');
insert into estados (descricao, uf) values ('Mato Grosso do Sul', 'MS');		 
insert into estados (descricao, uf) values ('Minas Gerais', 'MG');
insert into estados (descricao, uf) values ('Pará', 'PA');		 
insert into estados (descricao, uf) values ('Paraíba', 'PB');
insert into estados (descricao, uf) values ('Paraná', 'PR');		 
insert into estados (descricao, uf) values ('Pernambuco', 'PE');
insert into estados (descricao, uf) values ('Piauí', 'PI');		 
insert into estados (descricao, uf) values ('Rio de Janeiro', 'RJ');
insert into estados (descricao, uf) values ('Rio Grande do Norte', 'RN');		 
insert into estados (descricao, uf) values ('Rio Grande do Sul', 'RS');
insert into estados (descricao, uf) values ('Rondônia', 'RO');		 
insert into estados (descricao, uf) values ('Roraima', 'RR');
insert into estados (descricao, uf) values ('Santa Catarina', 'SC');		 
insert into estados (descricao, uf) values ('São Paulo', 'SP');
insert into estados (descricao, uf) values ('Sergipe', 'SE');		 
insert into estados (descricao, uf) values ('Tocantins', 'TO');
