-- Inserir materiais do estudo
insert into materiais_estudo (envia_certificado, nome, numero_ordem, qtd_estoque, tipo_envelope) values (false, 'INTRODUTÓRIA', 1, 0, 1);
insert into materiais_estudo (envia_certificado, nome, numero_ordem, qtd_estoque, tipo_envelope) values (true, 'DEUS TEM FALADO', 2, 0, 2);
insert into materiais_estudo (envia_certificado, nome, numero_ordem, qtd_estoque, tipo_envelope) values (true, 'CONHECENDO JESUS', 3, 0, 2);
insert into materiais_estudo (envia_certificado, nome, numero_ordem, qtd_estoque, tipo_envelope) values (true, 'ESTAS SÃO AS BOAS NOVAS', 4, 0, 2);
insert into materiais_estudo (envia_certificado, nome, numero_ordem, qtd_estoque, tipo_envelope) values (true, 'NASCIDOS DA ÁGUA E DO ESPÍRITO', 5, 0, 2);
insert into materiais_estudo (envia_certificado, nome, numero_ordem, qtd_estoque, tipo_envelope) values (false, 'O QUE A BÍBLIA DIZ 1', 6, 0, 2);
insert into materiais_estudo (envia_certificado, nome, numero_ordem, qtd_estoque, tipo_envelope) values (false, 'O QUE A BÍBLIA DIZ 2', 7, 0, 2);
insert into materiais_estudo (envia_certificado, nome, numero_ordem, qtd_estoque, tipo_envelope) values (false, 'O QUE A BÍBLIA DIZ 3', 8, 0, 2);
insert into materiais_estudo (envia_certificado, nome, numero_ordem, qtd_estoque, tipo_envelope) values (false, 'O QUE A BÍBLIA DIZ 4', 9, 0, 2);
insert into materiais_estudo (envia_certificado, nome, numero_ordem, qtd_estoque, tipo_envelope) values (false, 'O QUE A BÍBLIA DIZ 5', 10, 0, 2);
insert into materiais_estudo (envia_certificado, nome, numero_ordem, qtd_estoque, tipo_envelope) values (false, 'O QUE A BÍBLIA DIZ 6', 11, 0, 2);
insert into materiais_estudo (envia_certificado, nome, numero_ordem, qtd_estoque, tipo_envelope) values (false, 'O QUE A BÍBLIA DIZ 7', 12, 0, 2);
insert into materiais_estudo (envia_certificado, nome, numero_ordem, qtd_estoque, tipo_envelope) values (false, 'O QUE A BÍBLIA DIZ 8', 13, 0, 2);
insert into materiais_estudo (envia_certificado, nome, numero_ordem, qtd_estoque, tipo_envelope) values (false, 'O QUE A BÍBLIA DIZ 9', 14, 0, 2);
insert into materiais_estudo (envia_certificado, nome, numero_ordem, qtd_estoque, tipo_envelope) values (false, 'O QUE A BÍBLIA DIZ 10', 15, 0, 2);
insert into materiais_estudo (envia_certificado, nome, numero_ordem, qtd_estoque, tipo_envelope) values (true, 'O QUE A BÍBLIA DIZ 11', 16, 0, 2);
insert into materiais_estudo (envia_certificado, nome, numero_ordem, qtd_estoque, tipo_envelope) values (false, 'A IGREJA BÍBLICA 1', 17, 0, 2);
insert into materiais_estudo (envia_certificado, nome, numero_ordem, qtd_estoque, tipo_envelope) values (false, 'A IGREJA BÍBLICA 2', 18, 0, 2);
insert into materiais_estudo (envia_certificado, nome, numero_ordem, qtd_estoque, tipo_envelope) values (false, 'A IGREJA BÍBLICA 3', 19, 0, 2);
insert into materiais_estudo (envia_certificado, nome, numero_ordem, qtd_estoque, tipo_envelope) values (false, 'A IGREJA BÍBLICA 4', 10, 0, 2);
insert into materiais_estudo (envia_certificado, nome, numero_ordem, qtd_estoque, tipo_envelope) values (false, 'A IGREJA BÍBLICA 5', 21, 0, 2);
insert into materiais_estudo (envia_certificado, nome, numero_ordem, qtd_estoque, tipo_envelope) values (false, 'A IGREJA BÍBLICA 6', 22, 0, 2);
insert into materiais_estudo (envia_certificado, nome, numero_ordem, qtd_estoque, tipo_envelope) values (false, 'A IGREJA BÍBLICA 7', 23, 0, 2);
insert into materiais_estudo (envia_certificado, nome, numero_ordem, qtd_estoque, tipo_envelope) values (false, 'A IGREJA BÍBLICA 8', 24, 0, 2);
insert into materiais_estudo (envia_certificado, nome, numero_ordem, qtd_estoque, tipo_envelope) values (false, 'A IGREJA BÍBLICA 9', 25, 0, 2);
insert into materiais_estudo (envia_certificado, nome, numero_ordem, qtd_estoque, tipo_envelope) values (false, 'A IGREJA BÍBLICA 10', 26, 0, 2);
insert into materiais_estudo (envia_certificado, nome, numero_ordem, qtd_estoque, tipo_envelope) values (false, 'A IGREJA BÍBLICA 11', 27, 0, 2);
insert into materiais_estudo (envia_certificado, nome, numero_ordem, qtd_estoque, tipo_envelope) values (false, 'A IGREJA BÍBLICA 12', 28, 0, 2);
insert into materiais_estudo (envia_certificado, nome, numero_ordem, qtd_estoque, tipo_envelope) values (true, 'A IGREJA BÍBLICA 13', 29, 0, 2);
insert into materiais_estudo (envia_certificado, nome, numero_ordem, qtd_estoque, tipo_envelope) values (false, 'CRISTIANISMO EM AÇÃO 1', 30, 0, 2);
insert into materiais_estudo (envia_certificado, nome, numero_ordem, qtd_estoque, tipo_envelope) values (false, 'CRISTIANISMO EM AÇÃO 2', 31, 0, 2);
insert into materiais_estudo (envia_certificado, nome, numero_ordem, qtd_estoque, tipo_envelope) values (false, 'CRISTIANISMO EM AÇÃO 3', 32, 0, 2);
insert into materiais_estudo (envia_certificado, nome, numero_ordem, qtd_estoque, tipo_envelope) values (false, 'CRISTIANISMO EM AÇÃO 4', 33, 0, 2);
insert into materiais_estudo (envia_certificado, nome, numero_ordem, qtd_estoque, tipo_envelope) values (false, 'CRISTIANISMO EM AÇÃO 5', 34, 0, 2);
insert into materiais_estudo (envia_certificado, nome, numero_ordem, qtd_estoque, tipo_envelope) values (false, 'CRISTIANISMO EM AÇÃO 6', 35, 0, 2);
insert into materiais_estudo (envia_certificado, nome, numero_ordem, qtd_estoque, tipo_envelope) values (false, 'CRISTIANISMO EM AÇÃO 7', 36, 0, 2);
insert into materiais_estudo (envia_certificado, nome, numero_ordem, qtd_estoque, tipo_envelope) values (false, 'CRISTIANISMO EM AÇÃO 8', 37, 0, 2);
insert into materiais_estudo (envia_certificado, nome, numero_ordem, qtd_estoque, tipo_envelope) values (false, 'CRISTIANISMO EM AÇÃO 9', 38, 0, 2);
insert into materiais_estudo (envia_certificado, nome, numero_ordem, qtd_estoque, tipo_envelope) values (false, 'CRISTIANISMO EM AÇÃO 10', 39, 0, 2);
insert into materiais_estudo (envia_certificado, nome, numero_ordem, qtd_estoque, tipo_envelope) values (false, 'CRISTIANISMO EM AÇÃO 11', 40, 0, 2);
insert into materiais_estudo (envia_certificado, nome, numero_ordem, qtd_estoque, tipo_envelope) values (false, 'CRISTIANISMO EM AÇÃO 12', 41, 0, 2);
insert into materiais_estudo (envia_certificado, nome, numero_ordem, qtd_estoque, tipo_envelope) values (true, 'CRISTIANISMO EM AÇÃO 13', 42, 0, 2);
