-- Inserir materiais do estudo
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('INTRODUTÓRIA', 1, 1);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('DEUS TEM FALADO', 2, 2);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('CONHECENDO JESUS', 3, 2);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('ESTAS SÃO AS BOAS NOVAS', 4, 2);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('NASCIDOS DA ÁGUA E DO ESPÍRITO', 5, 2);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('O QUE A BÍBLIA DIZ 1', 6, 2);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('O QUE A BÍBLIA DIZ 2', 7, 2);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('O QUE A BÍBLIA DIZ 3', 8, 2);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('O QUE A BÍBLIA DIZ 4', 9, 2);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('O QUE A BÍBLIA DIZ 5', 10, 2);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('O QUE A BÍBLIA DIZ 6', 11, 2);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('O QUE A BÍBLIA DIZ 7', 12, 2);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('O QUE A BÍBLIA DIZ 8', 13, 2);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('O QUE A BÍBLIA DIZ 9', 14, 2);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('O QUE A BÍBLIA DIZ 10', 15, 2);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('O QUE A BÍBLIA DIZ 11', 16, 2);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('A IGREJA BÍBLICA 1', 17, 3);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('A IGREJA BÍBLICA 2', 18, 3);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('A IGREJA BÍBLICA 3', 19, 3);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('A IGREJA BÍBLICA 4', 20, 3);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('A IGREJA BÍBLICA 5', 21, 3);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('A IGREJA BÍBLICA 6', 22, 3);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('A IGREJA BÍBLICA 7', 23, 3);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('A IGREJA BÍBLICA 8', 24, 3);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('A IGREJA BÍBLICA 9', 25, 3);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('A IGREJA BÍBLICA 10', 26, 3);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('A IGREJA BÍBLICA 11', 27, 3);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('A IGREJA BÍBLICA 12', 28, 3);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('A IGREJA BÍBLICA 13', 29, 3);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('CRISTIANISMO EM AÇÃO 1', 30, 3);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('CRISTIANISMO EM AÇÃO 2', 31, 3);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('CRISTIANISMO EM AÇÃO 3', 32, 3);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('CRISTIANISMO EM AÇÃO 4', 33, 3);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('CRISTIANISMO EM AÇÃO 5', 34, 3);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('CRISTIANISMO EM AÇÃO 6', 35, 3);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('CRISTIANISMO EM AÇÃO 7', 36, 3);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('CRISTIANISMO EM AÇÃO 8', 37, 3);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('CRISTIANISMO EM AÇÃO 9', 38, 3);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('CRISTIANISMO EM AÇÃO 10', 39, 3);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('CRISTIANISMO EM AÇÃO 11', 40, 3);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('CRISTIANISMO EM AÇÃO 12', 41, 3);
insert into materiais_estudo (nome, numero_ordem, tipo_envelope) values ('CRISTIANISMO EM AÇÃO 13', 42, 3);
